config/routes.rb
Rails.application.routes.draw do

  resources :genres
  get "signin" => "sessions#new"
  resource :session  
  get "signup" => "users#new"
  resources :users
  root "movies#index"
  get "movies/filter/:scope" => "movies#index", as: "filtered_movies"
  resources :movies do
    resources :reviews
    resources :favorites
  end

  # get "movies" => "movies#index"
  # get "movies/new" => "movies#new"
  # get "movies/:id" => "movies#show", as: "movie"
  # get "movies/:id/edit" => "movies#edit", as: "edit_movie"
  # patch "movies/:id" => "movies#update"

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
	<p>
		Copyright &copy; 2016
		<%= link_to("Tijo Thomas", "http://tijo-thomas.github.io") %>
	</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
	<div id="masthead">
		<h1><%= link_to("Flix", root_path) %></h1>
		<nav>
			<p>
				<!-- 
				Calls the current_user method from the
				application_helper.rb file to get the
				current user from the database.
				-->
				<% if current_user %>
					<%= link_to(current_user.name, user_path(current_user.id)) %>
					<%= link_to("Account Settings", edit_user_path(current_user.id), class: "button") %>
					<%= link_to("Sign Out", session_path(current_user.id), method: :delete, class: "button") %>
				<% else %>
					<%= link_to("Sign Up", signup_path, class: "button") %>
					<%= link_to("Sign In", signin_path, class: "button") %>
				<% end %>
			</p>
		</nav>
	</div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
	<nav>
		<ul>
			<li class="all-movies">
				<%= link_to("Released", movies_path, class: "button") %>
			</li>
			<li class="all-movies">
				<%= link_to("Hits", filtered_movies_path(:hits), class: "button") %>
			</li>
			<li class="all-movies">
				<%= link_to("Flops", filtered_movies_path(:flops), class: "button") %>
			</li>
			<li class="all-movies">
				<%= link_to("Upcoming", filtered_movies_path(:upcoming), class: "button") %>
			</li>
			<li class="all-movies">
				<%= link_to("Recent", filtered_movies_path(:recent), class: "button") %>
			</li>
			<% if current_user_admin? %>
				<li class="create-movie">
					<%= link_to("Add New Movie", new_movie_path, class: "button") %>
				</li>
			<% end %>
		</ul>
	</nav>
	<!-- 
		This displays the content that was stored using
		the content_for helper method from the movie show
		template.
	 -->
	<%= content_for(:sidebar_extras) %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= page_title %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>

		<div id="wrapper">
			<!-- Renders flash partial that accounts for all types(notice, alert, etc.). -->
			<%= render "layouts/flashes" %>
			<div id="container">
				<section id="sidebar">
					<%= render "layouts/sidebar" %>
				</section>
				<section id="content">
					<%= yield %>
				</section>
			</div>
		</div>
		<%= render "layouts/footer" %>
	</body>
</html>